<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find description)/urdf/controllers/diff_drive_controller.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/property/robot_property.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/mech/wheel.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/mech/caster_wheel.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/sensors/laser.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/sensors/camera.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/sensors/range_sensor.urdf.xacro" />

  <xacro:diff_drive_controller/>

  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_x="${wheel_pos_x}"
    wheel_pos_z="${wheel_pos_z}"
/>

  <xacro:wheel 
    side="left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:caster_wheel 
      side="right"
      mass="0.01"
      base_length="${base_length}" 
      base_width="${base_width}"
      base_height="${base_height}"
      wheel_radius="${wheel_radius}" 
      wheel_pos_z="${wheel_pos_z}" 
    />

    <xacro:caster_wheel 
      side="left"
      mass="0.01"
      base_length="${base_length}" 
      base_width="${base_width}"
      base_height="${base_height}"
      wheel_radius="${wheel_radius}" 
      wheel_pos_z="${wheel_pos_z}" 
    />  

  <xacro:camera/>
  <xacro:imu/>
  <xacro:laser/>

  <xacro:range_sensor 
    pos="center"
    pos_x="0.1725" 
    pos_y=" 0"
    pos_z="0.01" 
    pitch="0"
    yaw="0"
  />
  <xacro:range_sensor 
    pos="left"
    pos_x="0.1625" 
    pos_y="0.08"
    pos_z="0.01" 
    pitch="0"
    yaw="0.6106"
  />
  <xacro:range_sensor 
    pos="right"
    pos_x="0.1625" 
    pos_y="-0.08"
    pos_z="0.01" 
    pitch="0"
    yaw="-0.6106"
  />
  

  <!-- <xacro:depth_sensor>
    <xacro:insert_block name="depth_sensor_pose" />
  </xacro:depth_sensor>

  <xacro:diff_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_radius="${wheel_radius}"
    wheel_torque="${wheel_torque}"
  /> -->

</robot>